{
    'name': 'Account Advance',
    'version': '18.0.1.0.0',
    'summary': 'Account Advance Management',
    'description': 'Account Advance Request, Payment and Clearing',
    'category': 'Accounting',
    'author': 'Perfect Blending',
    'website': 'https://www.perfectblending.com',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'account',
        'hr',
        'payment_method',
        'account_cheque',
        'l10n_th_account_tax',
        'multi_branch_management_aagam',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/advance_security.xml',
        'views/account_advance_request_view.xml',
        'views/account_advance_view.xml',
        'views/account_advance_clear_view.xml',
        'views/res_config_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
